services:
  app:
    image: hyperf-skeleton
    # user: "${UID}:${GID}"
    build:
      context: .
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    networks:
      - hyperf
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false
      - APP_NAME=app
      - DB_DRIVER=pgsql
      # - DB_HOST=127.0.0.1
      - DB_HOST=pgsql
      - DB_PORT=5432
      - DB_DATABASE=app
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
      - DB_CHARSET=utf8
      - DB_PREFIX=
      - REDIS_HOST=valkey
      - REDIS_AUTH=(null)
      - REDIS_PORT=6379
      - REDIS_DB=0

  pgsql:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    # ports:
    #   - 5432:5432
    networks:
      - hyperf
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "app"
        - "-U"
        - "postgres"
      retries: 3
      timeout: 5s

volumes:
  database_data:

networks:
  hyperf:
    driver: bridge
