services:
  app:
    image: hyperf-skeleton
    build:
      context: .
    # user: "${UID}:${GID}"
    volumes:
      - ./:/opt/www
    ports:
      - 9501:9501
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - hyperf
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

  pgsql:
    image: postgres:17.4-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-root}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # - ".devcontainer/database/create-testing-database.sql:/docker-entrypoint-initdb.d/10-create-testing-database.sql"
    networks:
      - hyperf
    healthcheck:
      test:
        - CMD
        - pg_isready
        - "-q"
        - "-d"
        - "app"
        - "-U"
        - "postgres"
      retries: 3
      timeout: 5s

volumes:
  database_data:

networks:
  hyperf:
    driver: bridge
