@host=localhost
@createdAt = {{$datetime iso8601}}
# @modifiedBy = {{$processEnv USERNAME}}
@contentType = application/json

Host: {{ host }}
Content-Type: {{ contentType }}

###

GET /auth/authenticate
Host: {{ host }}
Content-Type: {{ contentType }}
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSlBEVldLOFA3NDVEMVpLU0U0MUQ5N0Q3Iiwic2Vzc2lvbl9pZCI6IjAxSlBHNEhGWkgxR01COUtXUENGMUhCMU1LIiwicmVzb3VyY2UiOiJhdXRob3JpemF0aW9uIiwiaWF0IjoxNzQyMTUwODc3LCJleHAiOjE3NDIxNTQ0Nzd9.mnLXi_Ch5vyDSdTQxjyDohNcjSiN6gGy7s_g3JR191U

###

POST /auth/login
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "email": "admin@example.com",
    "password": "P@ssw0rD"
}

###

POST /auth/register
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "name": "Admin",
    "email": "admin2@example.com",
    "password": "P@ssw0rD",
    "password_confirmation": "P@ssw0rD"
}

###

POST /auth/verify
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSlBEVldLOFA3NDVEMVpLU0U0MUQ5N0Q3Iiwic2Vzc2lvbl9pZCI6IjAxSlBEV0VSNkZSTVBSNjgxWTE2NTVFVkRFIiwicmVmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MjA3NTI4OSwiZXhwIjoxNzQyMDc4ODg5fQ.ra_f6EOcT80RDpimspUHy76RoPPTuaeaV_AyinxROtk"
}

###

POST /auth/reverify
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "email": "admin10@example.com"
}

###

POST /auth/forgot
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "email": "admin10@example.com"
}


###


POST /auth/reset
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSlBEVldLOFA3NDVEMVpLU0U0MUQ5N0Q3Iiwic2Vzc2lvbl9pZCI6IjAxSlBHNEhGWkgxR01COUtXUENGMUhCMU1LIiwicmVzb3VyY2UiOiJhdXRob3JpemF0aW9uIiwiaWF0IjoxNzQyMTUwODc3LCJleHAiOjE3NDIxNTQ0Nzd9.mnLXi_Ch5vyDSdTQxjyDohNcjSiN6gGy7s_g3JR191U",
    "password": "P@ssw0rD",
    "password_confirmation": "P@ssw0rD"
}


###


POST /auth/refresh
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSlBEVldLOFA3NDVEMVpLU0U0MUQ5N0Q3Iiwic2Vzc2lvbl9pZCI6IjAxSlBHNEhGWkgxR01COUtXUENGMUhCMU1LIiwicmVzb3VyY2UiOiJhdXRob3JpemF0aW9uIiwiaWF0IjoxNzQyMTUwODc3LCJleHAiOjE3NDIxNTQ0Nzd9.mnLXi_Ch5vyDSdTQxjyDohNcjSiN6gGy7s_g3JR191U"
}


###
GET /sessions
Host: {{ host }}
Content-Type: {{ contentType }}
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSlBEVldLOFA3NDVEMVpLU0U0MUQ5N0Q3Iiwic2Vzc2lvbl9pZCI6IjAxSlBHNEhGWkgxR01COUtXUENGMUhCMU1LIiwicmVzb3VyY2UiOiJhdXRob3JpemF0aW9uIiwiaWF0IjoxNzQyMTUwODc3LCJleHAiOjE3NDIxNTQ0Nzd9.mnLXi_Ch5vyDSdTQxjyDohNcjSiN6gGy7s_g3JR191U
