@host=localhost
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@contentType = application/json

Host: {{ host }}
Content-Type: {{ contentType }}


###

GET {{host}}/authenticate HTTP/1.1
content-type: {{contentType}}

###

POST /auth/login
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "email": "admin@example.com",
    "password": "P@ssw0rD123"
}

###

POST /auth/register
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "name": "Admin",
    "email": "admin4@example.com",
    "password": "P@ssw0rD",
    "password_confirmation": "P@ssw0rD"
}

###

POST /auth/verify
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSk5YSDQzODE2VzlWREpLNzAyQlpCVDg3IiwiaWF0IjoxNzQxNTQwNjc3LCJleHAiOjE3NDE1NDI0Nzd9.SgSbfPrkW0VKfofe_dRcWHIbYw9hvsE_p_e8j9aE56g"
}

###

POST /auth/reverify
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "email": "admin@example.com"
}

###

POST /auth/forgot
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "email": "admin@example.com"
}


###


POST /auth/reset
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSk5YSDQzODE2VzlWREpLNzAyQlpCVDg3IiwiaWF0IjoxNzQxNTYzNzA0LCJleHAiOjE3NDE1NjU1MDR9.7grQj82U4jbAkR-D8YjZKuo3O1u5n0mr-A1uvvGSrB8",
    "password": "P@ssw0rD123",
    "password_confirmation": "P@ssw0rD123"
}


###


POST /auth/refresh
Host: {{ host }}
Content-Type: {{ contentType }}

{
    "token": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSk5YSDQzODE2VzlWREpLNzAyQlpCVDg3IiwiaWF0IjoxNzQxNTYzODMxLCJleHAiOjE3NDE1NjU2MzEsInJlZnJlc2giOnRydWV9.XMNk3DEEuZ2xXp4k0ZeqLHFt48-MYqRWjMj4lpBucWQ"
}
