@host=localhost
@contentType = application/json

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSlBEVldLOFA3NDVEMVpLU0U0MUQ5N0Q3Iiwic2Vzc2lvbl9pZCI6IjAxSlBFQVFRNkhBQjFaMlBDSDk2VlFWUEJEIiwicmVzb3VyY2UiOiJhdXRob3JpemF0aW9uIiwiaWF0IjoxNzQyMDkwMjYzLCJleHAiOjE3NDIwOTM4NjN9.xzHhwmc9Vjw8FHl5hVJjPXOGmsqu2enNt00au437NpA

###

GET /user/me
Host: {{ host }}
Content-Type: {{ contentType }}
Authorization: Bearer {{ token }}
