@host=localhost
@contentType = application/json

@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjAxSlBEVldLOFA3NDVEMVpLU0U0MUQ5N0Q3Iiwic2Vzc2lvbl9pZCI6IjAxSlBGTTk2UE1aVjgzTTNDSjFIRTRSVEZXIiwicmVzb3VyY2UiOiJhdXRob3JpemF0aW9uIiwiaWF0IjoxNzQyMTMzODI4LCJleHAiOjE3NDIxMzc0Mjh9.3JOMfpRbNiGHYiDnj432pO2GzdUPComlCho2OVMNLOA

###

GET /user/me
Host: {{ host }}
Content-Type: {{ contentType }}
Authorization: Bearer {{ token }}
