@host=http://localhost
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@contentType = application/json

###
GET {{host}}/
content-type: {{contentType}}


###
GET {{host}}/health
content-type: {{contentType}}
